apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: nietakipawel/my_git_operator:latest
          imagePullPolicy: Always
          command: ["kopf", "run", "/app/operator.py"]
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: github-token
